# Generated by Django 4.2.7 on 2023-11-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website_app', '0002_show_episode_show_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='episode',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='show',
            name='season',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
