# Generated by Django 4.2.7 on 2023-11-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website_app', '0003_alter_show_episode_alter_show_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
