# Generated by Django 4.2.7 on 2023-11-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website_app', '0004_show_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='synopis',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
