# Generated by Django 4.2.7 on 2023-11-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website_app', '0005_show_synopis'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='language',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='show',
            name='synopis',
            field=models.TextField(blank=True),
        ),
    ]
