# Generated by Django 4.2.7 on 2023-11-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website_app', '0006_show_language_alter_show_synopis'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='streaming',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
